//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MEOServer.Models
{
    public partial class Category
    {
        public Category()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime LastModifiedBy { get; set; }
        public string LastModifiedOn { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
    
}
