//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MEOServer.Models
{
    public partial class Rating
    {
        public Rating()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public double Value { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
    
}
